"""auto-vote

Revision ID: e970cc73cc73
Revises: b1fdf3b59168
Create Date: 2024-04-29 17:36:11.979211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = 'e970cc73cc73'
down_revision: Union[str, None] = 'b1fdf3b59168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
